TesAmerica/TesAmerica/Models/ErrorViewModel.cs
namespace TesAmerica.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesAmerica/TesAmerica/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TesAmerica.Models;

namespace TesAmerica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesAmerica/TesAmerica/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;

namespace TesAmerica.Controllers
{
    public class PedidoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TesAmerica/TesAmerica/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using TesAmerica.LogicaNegocios.Dominio;
using TesAmerica.LogicaNegocios.Servicio;

namespace TesAmerica.Controllers
{
    public class VentaController : Controller
    {
        VentaService ventaService =  new VentaService();
        public IActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Acumulado(DateTime fechaInicial, DateTime fechaFinal)
        {

            List<AcumuladoVenta> acumulados = ventaService.Acumulado(fechaInicial, fechaFinal);
            return Json(acumulados);

        }

        public IActionResult ComisionVendedor()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Comision(DateTime fecha)
        {

            List<Vendedor> vendedors = ventaService.VendedorComision(fecha);
            return Json(vendedors);

        }

    }
}

TesAmerica/TesAmerica/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TesAmerica/TesAmerica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TesAmerica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TesAmerica.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesAmerica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Index"> Acumulado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="ComisionVendedor">Comision</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TesAmerica/TesAmerica/Views/Venta/Acumulado.cshtml
@using TesAmerica.LogicaNegocios.Dominio;


@{
    var Acumulado = ViewData["Acumulado"] as List<AcumuladoVenta>;
}

<div class="text-center">
    <h1 class="display-4"> Acumulado</h1>
</div>

@if (ViewData["Acumulado"] != null && ((List<AcumuladoVenta>)ViewData["Acumulado"]).Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>Nombre Departamento</th>
                <th>Acumulado</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in (List<AcumuladoVenta>)ViewData["Acumulado"])
            {
                <tr>
                    <td>@item.NombreDepartamento</td>
                    <td>@item.Acumulado</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No se encontraron registros.</p>
}

TesAmerica/TesAmerica/Views/Venta/ComisionVendedor.cshtml
@using TesAmerica.LogicaNegocios.Dominio;

<div class="text-center">
    <h1 class="display-4">Consion  x Vendedor</h1>
</div>

<div class="container text-center">

    <div class="card shadow-lg mb-5 mt-5 bg-white rounded p-3">
        <form id="formularioComision">
            <label for="fechaInicial">Fecha</label>
            <input type="date" id="fecha" name="fecha" placeholder="Fecha Inicial" />

            <button type="button" id="enviarBtn">Enviar</button>
        </form>
    </div>
    <!-- Tabla para mostrar los resultados -->
    <div class="mt-4 card">
        <table class="table table-bordered table-striped" id="tablaAcumulado" style="display: none;">
            <thead>
                <tr>
                    <th>Codigo Vendedor</th>
                    <th>Nombre </th>
                    <th>Comision </th>
                </tr>
            </thead>
            <tbody id="cuerpoTabla"></tbody>
        </table>
    </div>


</div>

<script>
    document.getElementById("enviarBtn").addEventListener("click", function () {
        var fecha = document.getElementById("fecha").value;

        var formData = new FormData();
        formData.append("fecha", fecha);
       

        fetch('/Venta/Comision', {
            method: 'POST',
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                var cuerpoTabla = document.getElementById("cuerpoTabla");
                cuerpoTabla.innerHTML = '';

                if (data.length === 0) {
                    cuerpoTabla.innerHTML = '<tr><td colspan="2">No tiene resultados disponibles</td></tr>';
                } else {
                    data.forEach(item => {
                        cuerpoTabla.innerHTML += `
                                <tr>
                                        <td>${item.codvend}</td>
                                        <td>${item.nombre}</td>
                                            <td>${item.comision}</td>

                                </tr>
                            `;
                    });
                }

                document.getElementById("tablaAcumulado").style.display = "table";
            })
            .catch(error => {
                console.error('Error:', error);
            });
    });
</script>

TesAmerica/TesAmerica/Views/Venta/Index.cshtml
@using TesAmerica.LogicaNegocios.Dominio;

<div class="text-center">
    <h1 class="display-4">Acumulado</h1>
</div>

<div class="container text-center">

    <div class="card shadow-lg mb-5 mt-5 bg-white rounded p-3">
        <form id="formularioAcumulado">
            <label for="fechaInicial">Fecha Inicial:</label>
            <input type="date" id="fechaInicial" name="fechaInicial" placeholder="Fecha Inicial" />

            <label for="fechaFinal">Fecha Final:</label>
            <input type="date" id="fechaFinal" name="fechaFinal" placeholder="Fecha Final" />

            <button type="button" id="enviarBtn">Enviar</button>
        </form>
    </div>

    <!-- Tabla para mostrar los resultados -->
    <div class="mt-4 card">
        <table class="table table-bordered table-striped" id="tablaAcumulado" style="display: none;">
            <thead>
                <tr>
                    <th>Nombre Departamento</th>
                    <th>Acumulado</th>
                </tr>
            </thead>
            <tbody id="cuerpoTabla"></tbody>
        </table>
    </div>
</div>
<script>
    document.getElementById("enviarBtn").addEventListener("click", function () {
        var fechaInicial = document.getElementById("fechaInicial").value;
        var fechaFinal = document.getElementById("fechaFinal").value;

        var formData = new FormData();
        formData.append("fechaInicial", fechaInicial);
        formData.append("fechaFinal", fechaFinal);

        fetch('/Venta/Acumulado', {
            method: 'POST',
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                var cuerpoTabla = document.getElementById("cuerpoTabla");
                cuerpoTabla.innerHTML = '';

                if (data.length === 0) {
                    cuerpoTabla.innerHTML = '<tr><td colspan="2">No tiene resultados disponibles</td></tr>';
                } else {
                    data.forEach(item => {
                        cuerpoTabla.innerHTML += `
                            <tr>
                                <td>${item.nombreDepartamento}</td>
                                <td>${item.acumulado}</td>
                            </tr>
                        `;
                    });
                }

                document.getElementById("tablaAcumulado").style.display = "table";
            })
            .catch(error => {
                console.error('Error:', error);
            });
    });
</script>